---
k3s_cluster:
  children:
    server:
      hosts:
        prod1:
          ansible_user: user
          ansible_host: 192.168.0.2
    agent:
      hosts:
        prod2:
          ansible_user: user
          ansible_host: 192.168.0.3
