---
# tasks file for k3s_agent
- name: Set platform/version specific variables
  ansible.builtin.include_vars: "{{ __rolename_vars_file }}"
  loop:
    - "{{ ansible_facts.os_family }}.yml"
    - "{{ ansible_facts.distribution }}.yml"
    - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_major_version }}.yml"
    - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_version }}.yml"
  vars:
    __rolename_vars_file: "{{ role_path }}/vars/{{ item }}"
  when: __rolename_vars_file is file

- name: Install k3s agent
  when: k3s_prepare_needs_install is defined and k3s_prepare_needs_install and "agent" in group_names
  vars:
    k3s_agent_token: '{{ lookup("file", inventory_dir + "/files/" + k3s_server_env + "-node-token") }}'
    k3s_server_url: '{{ lookup("file", inventory_dir + "/files/" + k3s_server_env + "-server-url") }}'
  block:
    - name: Get variables
      ansible.builtin.debug:
        var: k3s_agent_token
    - name: Install k3s agent
      ansible.builtin.command: "{{ k3s_prepare_script_path }}"
      environment:
        K3S_URL: "{{ k3s_server_url }}"
        K3S_TOKEN: "{{ k3s_agent_token }}"
      args:
        creates: "{{ k3s_agent_bin_path }}"
